
development:
  sessions:
    default:
      database: ish_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: ish_production
      hosts:
        - 10.0.0.134:27017
        
test:
  sessions:
    default:
      database: ish_test
      hosts:
        - localhost:27017